In [1]:
import numpy as np

In [2]:
weights_list = [150, 180, 250, 210]

In [5]:
weights_np = np.array(weights_list)

In [4]:
type(weights_list)

list

In [6]:
type(weights_np)

numpy.ndarray

In [7]:
weights_list + weights_list

[150, 180, 250, 210, 150, 180, 250, 210]

In [8]:
weights_np + weights_np

array([300, 360, 500, 420])

In [9]:
weights_np - weights_np

array([0, 0, 0, 0])

In [10]:
weights_list * 3

[150, 180, 250, 210, 150, 180, 250, 210, 150, 180, 250, 210]

In [11]:
weights_np *3

array([450, 540, 750, 630])

In [13]:
np.array([2, 5, True , False])

array([2, 5, 1, 0])

# Subsetting

In [18]:
weights_np

array([150, 180, 250, 210])

In [14]:
weights_np[0]

150

In [16]:
weights_np[-1]

210

In [17]:
weights_np[0:3]

array([150, 180, 250])

In [19]:
weights_np[-3:-1]

array([180, 250])

# Comparisons

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,3,2,2])
a

array([1, 2, 3, 4, 5])

In [22]:
b

array([5, 6, 3, 2, 2])

In [23]:
a > b

array([False, False, False,  True,  True])

In [24]:
a == b

array([False, False,  True, False, False])

In [25]:
a <= b

array([ True,  True,  True, False, False])

In [26]:
a != b

array([ True,  True, False,  True,  True])

In [29]:
a

array([1, 2, 3, 4, 5])

In [28]:
a < 5

array([ True,  True,  True,  True, False])

# Logical indexing

In [30]:
a

array([1, 2, 3, 4, 5])

In [32]:
a < 5

array([ True,  True,  True,  True, False])

In [33]:
a[0:4]

array([1, 2, 3, 4])

In [34]:
a[a<5]

array([1, 2, 3, 4])

In [35]:
a == b

array([False, False,  True, False, False])

In [36]:
a[a==b]

array([3])

In [37]:
b[a==b]

array([3])

In [38]:
a<b

array([ True,  True, False, False, False])

In [39]:
b[a<b]

array([5, 6])

In [40]:
b

array([5, 6, 3, 2, 2])

In [41]:
a

array([1, 2, 3, 4, 5])