In [1]:
import numpy as np

In [4]:
x = [list(range(0,6)),list(range(9,15)),list(range(20, 26))]

In [5]:
x

[[0, 1, 2, 3, 4, 5], [9, 10, 11, 12, 13, 14], [20, 21, 22, 23, 24, 25]]

In [8]:
xnp = np.array(x)
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

# Indexing

In [9]:
x[0]

[0, 1, 2, 3, 4, 5]

In [10]:
x[0][1]

1

In [11]:
x[0][-1]

5

In [13]:
xnp[0][1]

1

In [14]:
xnp[0][-1]

5

In [15]:
xnp[0, -1]

5

In [16]:
xnp[0,1]

1

In [17]:
x[0,1]

TypeError: list indices must be integers or slices, not tuple

# Slicing

In [20]:
x[0:1, 3:5]

TypeError: list indices must be integers or slices, not tuple

In [21]:
x[0:2]

[[0, 1, 2, 3, 4, 5], [9, 10, 11, 12, 13, 14]]

In [22]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [23]:
xnp[0:2, 1:4]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [24]:
xnp[0]

array([0, 1, 2, 3, 4, 5])

In [25]:
xnp[1, 3:5]

array([12, 13])

# Logical Indexing

In [26]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [27]:
xnp > 10

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [28]:
xnp[xnp>10]

array([11, 12, 13, 14, 20, 21, 22, 23, 24, 25])

In [29]:
xnp[:, 2]

array([ 2, 11, 22])

In [30]:
xnp[:, 2] > 10

array([False,  True,  True])

In [31]:
xnp[:, 2][xnp[:, 2] > 10]

array([11, 22])

In [33]:
xnp[:, 2:5][xnp[:, 2:5] > 13]

array([22, 23, 24])

In [34]:
xnp

array([[ 0,  1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25]])

In [35]:
xnp[:, 2]

array([ 2, 11, 22])

In [38]:
xnp[2]

array([20, 21, 22, 23, 24, 25])

In [39]:
xnp[2, :]

array([20, 21, 22, 23, 24, 25])